  GNU nano 2.9.3                   install-elk.yml

---
- name: Config Elk VM with Docker
  hosts: elk
  become: true
  tasks:

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present
